#!/bin/bash

# deye v 1.0.2
# ©2022 barcek
# License: MIT
# @ github.com
# /barcek/deye

flags=()

append_flag() {
  flags+=("--allow-${1}")
}

if [ $1 == "all" ]; then
  append_flag "all"
else
  for (( i=0; i<${#1}; i++ )); do
    case ${1: $i:1} in
      e) append_flag "env";;
      f) append_flag "ffi";;
      h) append_flag "hrtime";;
      n) append_flag "net";;
      r) append_flag "read";;
      w) append_flag "write";;
      x) append_flag "run";;
      *) echo "No permission for character ${1: $i:1}";;
    esac
  done
fi

deno run ${flags[*]} ${@: 2}
